---
- name: install the latest version of APT Transport HTTPS
  become: yes
  apt:
    name: apt-transport-https
    state: latest

- name: add Kubernetes apt-key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  become: yes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: install the latest version of kubelet
  become: yes
  apt:
    name: kubelet
    state: latest
    update_cache: true